apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  # find all the pods, that are labeled with "app: expiration"
  selector:
    matchLabels:
      app: expiration
  # tell the k8s master, to create the pods with these configuration
  template:
    metadata:
      # define the label so other k8s objects can access it
      labels:
        app: expiration
    spec:
      containers:
        # name is just for logging purposes
        - name: expiration
          image: us.gcr.io/ticketing-dev-353110/expiration
          # envs are from k8s secrets
          env:
            # this is going to be the name of variable as it shows up inside of container, so stay consistent
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              # value is same as name of expiration pod
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: REDIS_PORT
              value: '6379'
# we don't need any network service
